"""add dono_id em equipamentos

Revision ID: 071deb88fd35
Revises: 98fd8e4a56b9
Create Date: 2026-09-17 19:58:11.491373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071deb88fd35'
down_revision: Union[str, Sequence[str], None] = '98fd8e4a56b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dono_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_equipamentos_dono', 'usuarios', ['dono_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipamentos_dono', type_='foreignkey')
        batch_op.drop_column('dono_id')

    # ### end Alembic commands ###
