"""Criando tabelas iniciais

Revision ID: 98fd8e4a56b9
Revises: 
Create Date: 2026-09-17 19:42:16.563203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fd8e4a56b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dti', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('numero_serie', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipamentos_dti'), ['dti'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipamentos_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipamentos_id'))
        batch_op.drop_index(batch_op.f('ix_equipamentos_dti'))

    op.drop_table('equipamentos')
    # ### end Alembic commands ###
