"""adiciona coluna departamento

Revision ID: f7b92e2feb71
Revises: 071deb88fd35
Create Date: 2026-09-17 20:25:05.641952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b92e2feb71'
down_revision: Union[str, Sequence[str], None] = '071deb88fd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.drop_column('departamento')

    # ### end Alembic commands ###
